### ISSUE TITLE
Change result when using engine

### ISSUE THREAD

**Issue by xneomac** [marp-team/marp-core#118] opened 2019-10-19 17:29 UTC
With the following files [engine.js](https://github.com/xneomac/marp-core-bug/blob/master/engine.js) and [index.md](https://github.com/xneomac/marp-core-bug/blob/master/index.md). I get different result if I execute `marp index.js`

![screenshot1](https://raw.githubusercontent.com/xneomac/marp-core-bug/master/screenshot1.png)

or `marp --engine ./engine.js index.md`

![screenshot2](https://raw.githubusercontent.com/xneomac/marp-core-bug/master/screenshot2.png)

I have found that the problem exist if I use the theme _default_ or _gaia_, _uncover_ seems to work correctly with this example. I guess the problem is coming from the theme, I can look into it but do you have any tips in where to search ?

**Comment by yhatt** [comment] 2019-10-19 19:55
Duplicate of #112. It would have fixed in #115.

Try a workaround introduced in https://github.com/marp-team/marp-cli/issues/168#issuecomment-538296723 and https://github.com/marp-team/marp-core/issues/112#issuecomment-543290569 until the next minor release is released.

**Closed by yhatt** 2019-10-19 19:55 UTC
